package com.jbk.day31File;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

public class FileProgram1 {
	public static void main(String[] args) throws IOException {
		String s = "This file is generated by FileProgram1";
		byte b [] = s.getBytes();
		
		File file = new File("C:\\Users\\anura\\eclipse-workspace\\JBK\\src\\com\\jbk\\day31File\\Generated text file\\file1.txt");
		
		FileOutputStream fos = new FileOutputStream(file);
		fos.write(b);
		fos.close();
		
		System.out.println("File Generated..");
		
	}

}
